# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./AutorizacionMiddleware/Autorizacion.Middleware
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./AutorizacionMiddleware/Autorizacion.Middleware
    - name: Pack      
      run: dotnet pack
      working-directory: ./AutorizacionMiddleware/Autorizacion.Middleware
      
    - uses: actions/upload-artifact@v3
      with:
        name: nuget
        if-no-files-found: error
        retention-days: 7
        path: /home/runner/work/SC-701-Paquetes/SC-701-Paquetes/AutorizacionMiddleware/Autorizacion.Middleware/bin/Release/*.nupkg

  release:
    runs-on: ubuntu-latest    
    needs: build
    steps:  
    #Push NuGet package to GitHub packages
    - name: Download nuget package artifact
      uses: actions/actions/download-artifact@v4
      with:
        name: nuget
    - name: Prep packages
      run: dotnet nuget add source --username Drojascode --password ${{ secrets.PAQUETES_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/yourusername/index.json"
    - name: Push package to GitHub packages 
      if: needs.build.outputs.CommitsSinceVersionSource > 0 #Only release if there has been a commit/version change  
      run: dotnet nuget push nugetPackage/*.nupkg --api-key ${{ secrets.PAQUETES_TOKEN }}  --source "github"
    
