# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./AutorizacionMiddleware/Autorizacion.Middleware
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./AutorizacionMiddleware/Autorizacion.Middleware
    - name: Pack      
      run: dotnet pack --configuration Release --output ${{ env.NuGetDirectory }}
      working-directory: ./AutorizacionMiddleware/Autorizacion.Middleware
      
    - uses: actions/upload-artifact@v3
      with:
        name: nuget
        if-no-files-found: error
        retention-days: 7
        path: ${{ env.NuGetDirectory }}/*.nupkg

